### ISSUE TITLE
Complete the workflow to contribute to EasyHPC

### ISSUE THREAD

**Issue by pescap** [pescap/EasyHPC#20]
In [github.rst](https://github.com/pescap/EasyHPC/blob/main/docs/source/github.rst) we have the following workflow for the moment:

- Fork
- Create a new branch
- Add changes
- Propose a PR and merge

Soon, we will proceed like this:

- Create an issue to suggest changes or enhancements to the code
- (Fork)
- Create a new branch
- Add the discussed changes
- Propose a PR and merge

Add new sections to [github](https://github.com/pescap/EasyHPC/blob/main/docs/source/github.rst) to explain how to create issues, discuss them, assign the issue to someone.

**Comment by pescap** [comment]
@Setol21

**Comment by pescap** [comment]
Maybe explain how to set upstream, and how to keep your forked repository up to date (see e.g., [this article](https://docs.github.com/es/pull-requests/collaborating-with-pull-requests/working-with-forks/configuring-a-remote-for-a-fork)).

**Comment by Setol21** [comment]
Okay, I will keep that in mind, I just made a pull request for the GitHub 'issue' section.
Later on I will add those things to the documentation.

**Comment by Setol21** [comment]
@pescap, thank you for your patience!
If you have any ideas in mind to fulfill/enhace the GitHub section I will be more than happy! 😄 (I'm exploring on how to enhace it too)

**Comment by pescap** [comment]
#25

**Comment by pescap** [comment]
#25
