### ISSUE TITLE
Add an a Sphinx tutorial

### ISSUE THREAD

**Issue by agustinesoto** [pescap/EasyHPC#23]
I think is  necessary to add a brief introduction to Sphinx an how to use with your local machine and do testing.

Like this blog
https://mattermost.com/blog/locally-working-with-sphinx/

**Comment by Ehaw04** [comment]
I would like to take this issue. I think I will merge this tutorial into the cicd.rst, but I will wait for confirmation on where to put it before I send the pull request.

**Comment by pescap** [comment]
@Ehaw04: Check #36, and then you could add what you did, to complement this first version

**Comment by pescap** [comment]
Hi @Ehaw04, how are you going with this?

**Comment by pescap** [comment]
@Ehaw04

**Comment by Ehaw04** [comment]
Oh! I didn’t noticed that i was assigned to this. I will review this asap!
