### ISSUE TITLE
DeepXDE section

### ISSUE THREAD

**Issue by pescap** [pescap/EasyHPC#27]
Understand and sum up how to solve simple forward problems with DeepXDE. 

Examples:
- [Helmholtz 2D](https://deepxde.readthedocs.io/en/latest/demos/pinn_forward/helmholtz.2d.dirichlet.html)
- [Diffusion](https://deepxde.readthedocs.io/en/latest/demos/pinn_forward/diffusion.1d.html)

**Comment by Setol21** [comment]
I would like to take this issue.

- For now I'm working on adding:

Solving a Time-independent section:
    Helmholtz 2D example.

Time-dependent section:
    Diffusion example.
