### ISSUE TITLE
Add documentation about how horovod works

### ISSUE THREAD

**Issue by pescap** [pescap/EasyHPC#35]
[Here](https://github.com/pescap/EasyHPC/blob/main/docs/source/horovod.rst). 

It could be interesting to add bibliography (from academia, and blogs (Medium, etc...). 

Try to find the best articles to understand Horovod, how it works (technically), its structure. 

I suggest to list the references, for example:

### Documentation

[Meet Horovod: Uber’s Open Source Distributed Deep Learning Framework for TensorFlow](https://eng.uber.com/horovod/)
Add a summary of what matters/you learnt or understood in this article

[Distributed Deep Learning with Horovod](https://developer.download.nvidia.com/video/gputechconf/gtc/2019/presentation/s9321-distributed-deep-learning-with-horovod.pdf) 
summary

and so on. 

You can start with these references (and add your notes gradually):

https://towardsdatascience.com/distributed-deep-learning-with-horovod-2d1eea004cb2
https://arxiv.org/pdf/1706.02677.pdf
Horovod Article: https://arxiv.org/pdf/1802.05799.pdf
Uber presentation: https://developer.download.nvidia.com/video/gputechconf/gtc/2019/presentation/s9321-distributed-deep-learning-with-horovod.pdf

Add more references if you find more.

Important. Read: https://github.com/lululxvi/deepxde/issues/39

**Comment by pescap** [comment]
Horovod accelerated PINNs: [NeuralSolvers](https://github.com/ComputationalRadiationPhysics/NeuralSolvers). 
Read the paper, comment it, and understand the code. We aim to implement the same ideas with DeepXDE.

Read: https://eng.uber.com/michelangelo-machine-learning-platform/

**Comment by Ehaw04** [comment]
[Uber Open Summit 2018] Horovod: Deep Learning distribuido en 5 líneas de Python:

https://www.youtube.com/watch?v=4y0TDK3KoCA&t=900s&ab_channel=UberEngineering

**Comment by pescap** [comment]
#58
