### ISSUE TITLE
Implement a 3 letter tag in the title of issues.

### ISSUE THREAD

**Issue by Ehaw04** [pescap/EasyHPC#39]
Inspired by the open source seen in class, I think this improvment will make the issues section more understandable and will help us classify issues. I suggest some subjects:

-[BUG]: for bug related issues with the code.
-[ENH]: to propose enhancement to the code.
-[REV]: to indicate that something needs to be reviewed or re done.
-[LOW]: to mark a low priority issue
-[HIG]: to mark a high priority issue

Theese are only examples of how we could implement this so i´m all ears to further suggestions and confirmation to put it in the documentation.

**Comment by Setol21** [comment]
Hi!

There's a workaround for this. You can go to the right panel and add ``Labels``, this is probably what you are looking for. Remember if there is no Labels that represent the content of your ``Issue``, you can create more and add them to your ``Issue``. 

🚀

**Comment by pescap** [comment]
So far I am not sure I understand why people use [] and labels. There is an explanation... Let me know if you find something.

According to labels:
I added a HPC label for the Horovod-HPC TID (@Setol21 @agustinesoto). 
I'll add an Inverse label for the Inverse-Problems TID (@Ehaw04 and Artemio)

**Comment by Setol21** [comment]
I will close this issue since is no longer important.
