### ISSUE TITLE
Tutorial on how to run DeepXDE with conda on a server

### ISSUE THREAD

**Issue by pescap** [pescap/EasyHPC#41]
Add some documentation about this.

**Comment by pescap** [comment]
Hi @agustinesoto, let me know you are doing with this issue.

**Comment by agustinesoto** [comment]
Hi prof, I've just made a pull request to this issue. 

If there is no comments I'll close the issue.

**Comment by agustinesoto** [comment]
I will update the section soon, but I'm gonna close the issue to focus on the pending task.
