### ISSUE TITLE
[Inverse] Reproduce the hPINN tutorials

### ISSUE THREAD

**Issue by pescap** [pescap/EasyHPC#44]
Clone [this repository](https://github.com/lululxvi/hpinn) on the GPU cluster, and reproduce the examples here [e.g. holography_main](https://github.com/lululxvi/hpinn/blob/main/holography/holography_main.py).

**Comment by ArtemioA** [comment]
Professor,
I ran the the "holography_main.py" code and have this problem!
![image](https://user-images.githubusercontent.com/78178128/160963515-64c3e8ea-044e-48e2-aa29-291f1bae8004.png)

**Comment by ArtemioA** [comment]
I ran some examples in the DeepXDE repository,and i
successfully i optimized the neural network!!

**Comment by ArtemioA** [comment]
![image](https://user-images.githubusercontent.com/78178128/160964091-3424aefd-da32-4d5e-ab5c-8dcef22e9969.png)

**Comment by pescap** [comment]
- hpinn repository was created 8 months ago approximately.
- It sounds like the tutorials are no longer compatible with the new DeepXDE

My suggestions:
- Try to run the hpinn tutorials with an [older version](https://pypi.org/project/DeepXDE/#history) of DeepXDE, for example version `0.13.6`.
- Create an issue in the hpinn repository, to ask: (i) which version was used to run experiments, and showing the error, asking whether they could change the code to adapt it to new version.

**Comment by ArtemioA** [comment]
Professor,
i have the same problem.

![image](https://user-images.githubusercontent.com/78178128/161130141-9abb4b56-2918-4817-8993-ca2955bf1615.png)

*I will follow your instructions.*

**Comment by ArtemioA** [comment]
Professor,
Working!

![image](https://user-images.githubusercontent.com/78178128/161150828-8ab74da3-1324-4772-a48a-5b92cad17e66.png)

**Comment by ArtemioA** [comment]
Why will it be so slow? My partner recommends me to use the CPU.

**Comment by ArtemioA** [comment]
Professor,
what to do now?

**Comment by pescap** [comment]
> Professor, what to do now?

You have several open Issues that are assigned to you. You can work on this for the moment.
I'll keep creating issues, to help you know what you have to do next. 
Pau
