### ISSUE TITLE
Individual tasks for the TID

### ISSUE THREAD

**Issue by pescap** [pescap/EasyHPC#45]
### 1st Meeting:

- Create an Issue:
  - [x] @agustinesoto 
  - [x] @ArtemioA 
  - [x] @Setol21 
  - [x] @Ehaw04 

- Send a Pull Request:
  - [x] @agustinesoto 
  - [x] @ArtemioA 
  - [x] @Setol21 
  - [x] @Ehaw04 

### 2nd Meeting:

- Log into the GPU cluster:
  - [x] @agustinesoto 
  - [x] @ArtemioA 
  - [x] @Setol21 
  - [x] @Ehaw04 

### 3rd Meeting:

- Install conda as user (GPU cluster)
  - [x] @agustinesoto 
  - [x] @ArtemioA 
  - [x] @Setol21 
  - [x] @Ehaw04 

- Set up a conda environnement (GPU cluster) with DeepXDE and TensorFlow 2.x
  - [x] @agustinesoto 
  - [x] @ArtemioA 
  - [x] @Setol21 
  - [x] @Ehaw04 

- Run DeepXDE examples (GPU cluster) 
  - [x] @agustinesoto 
  - [x] @ArtemioA 
  - [x] @Setol21 
  - [x] @Ehaw04 

### 4th Meeting:
- Read the DeepXDE paper and add your notes to the DeepXDE section
  - [x] @agustinesoto 
  - [x] @ArtemioA 
  - [x] @Setol21 
  - [x] @Ehaw04 

- Watch [this](https://www.youtube.com/watch?v=Wfgr1pMA9fY&ab_channel=MLPS-CombiningAIandMLwithPhysicsSciences) DeepXDE talk
  - [x] @agustinesoto 
  - [x] @ArtemioA 
  - [x] @Setol21 
  - [x] @Ehaw04 

- Watch [this](https://www.youtube.com/watch?v=iUu-F2AEUE0&ab_channel=INISeminarRoom1) PINNs talk
  - [x] @agustinesoto 
  - [x] @ArtemioA 
  - [x] @Setol21 
  - [x] @Ehaw04 

- Configure the vpn and connect to the GPU cluster via ssh from outside the campus
  - [x] @agustinesoto 
  - [x] @ArtemioA 
  - [x] @Setol21 
  - [x] @Ehaw04

**Comment by pescap** [comment]
To complete a task, you can send screenshots directly here. I grouped all the individual tasks together. Soon, I'll add project dependent tasks (HPC and Inverse). 

In parallel, keep adding contents to the docs (see Open Issues).

**Comment by Setol21** [comment]
![conda path](https://user-images.githubusercontent.com/69603395/159286132-a25e6f5a-f07d-44ef-bd62-cf32eb4d23bf.png)
![gpu_usage](https://user-images.githubusercontent.com/69603395/159286142-546989e0-8d41-4d2c-8d72-ae5336a34dc6.png)
![running via jupyter notebook](https://user-images.githubusercontent.com/69603395/159286144-c9083bd8-b7e2-49cc-b587-edd305c84037.png)
![usgin port 8889](https://user-images.githubusercontent.com/69603395/159286147-3221e728-be7e-4b52-9717-79551e02291b.png)

**Comment by Setol21** [comment]
There is my work:
- For the time, I'm just curious on how a jupyter notebook to run on a certain gpu, since it has been using multiple gpus with no purpose at all, the execution was surprisingly slow.
- In my environment I installed tensorflow-gpu, because with normal tensorflow it was using the CPU (all cores at 100%, whoops!).

**Comment by pescap** [comment]
(I am currently using port 8888)

**Comment by Ehaw04** [comment]
![server 3rd meeting](https://user-images.githubusercontent.com/101342356/159494103-79dba5ca-187c-4c91-883e-dcae700e9f62.png)
![server 3rd meeting 2](https://user-images.githubusercontent.com/101342356/159494118-46144988-9156-472f-a9e3-bcfad25a749f.png)

**Comment by Ehaw04** [comment]
I've managed to install conda, deepxde with tensorflow as a backend but ran out of time when I was trying to run an example. Hopefully I get it done on wednesday.

**Comment by pescap** [comment]
@Ehaw04 can you also confirm that you could ssh to the server from outside the university?

**Comment by Ehaw04** [comment]
@pescap just tried it but once I press enter it does nothing

**Comment by Ehaw04** [comment]
it says 

(base) elias@DESKTOP-CT76EAO:~$ ssh ehawas@10.30.229.4
ssh: connect to host 10.30.229.4 port 22: Connection timed out

**Comment by Ehaw04** [comment]
OK, now I connected succesfully to the cluster when I used Daniel's solution

**Comment by ArtemioA** [comment]
![image](https://user-images.githubusercontent.com/78178128/160251292-57575dc7-b581-4ea2-90db-2532140b8550.png)
I see the talk about the DeepXDE library and the math behind it

**Comment by ArtemioA** [comment]
![image](https://user-images.githubusercontent.com/78178128/160302262-493f4b73-6a10-4d19-a9a9-a1a2f4b19a78.png)

- Install conda as user (GPU cluster)

![image](https://user-images.githubusercontent.com/78178128/160302314-266636c7-c107-43b6-90c0-239ae1f009a7.png)

- Set up a conda environnement (GPU cluster) with DeepXDE and TensorFlow 2.x

![image](https://user-images.githubusercontent.com/78178128/160302308-77da441a-d7c5-4d88-a1ff-69c7b9f6bfb6.png)

- Configure the vpn and connect to the GPU cluster via ssh from outside the campus

**Comment by ArtemioA** [comment]
DeepXDE Paper Notes

https://kami.app/a2g-6AA-ENV-Shp
