### ISSUE TITLE
Set up multiple Jupyter or Docker sessions (ssh)

### ISSUE THREAD

**Issue by pescap** [pescap/EasyHPC#46]
See how to define ports at ssh level:

`ssh -L a:localhost:b user@10.30.229.4`
`jupyter notebook --port c`

`nvidia-docker run -v $(pwd):/root/shared -w "/root/shared" -p d:e pescapil/deepxde:latest`

The aim is knowing how to define `a,b,c,d`, for a given session.

**Comment by pescap** [comment]
Hi, I managed to do that. Assume that you want to run two `docker` images at the same time, on ports `8882` and `8883` for example.

**Port 8882* 

```
 ssh -L 8882:localhost:8882 user@my_ip_address 
 nvidia-docker run -v $(pwd):/root/shared -w "/root/shared" -p 0.0.0.0:8882:8888/tcp  pescapil/deepxde:latest
```
The `jupyter-notebook` url will appear as `my_ip_address/8888/?token=token`.
Replace `8888` by `8882` in this url. This is due to the Dockerfile exposing port `8888`. 

**Port 8883** 

```
 ssh -L 8883:localhost:8883 user@my_ip_address 
 nvidia-docker run -v $(pwd):/root/shared -w "/root/shared" -p 0.0.0.0:8883:8888/tcp  pescapil/deepxde:latest
```
The `jupyter-notebook` url will appear as `my_ip_address/8888/?token=token`.
Replace `8888` by `8883` in this url.

**Comment by pescap** [comment]
Let me know if it works with you. 
Then, I'll let you add the final steps to the `docs`.

**Comment by agustinesoto** [comment]
Thanks for the help, I was stuck with this issue.
I'm gonna test the commands and I will reply you soon.

**Comment by agustinesoto** [comment]
I've just test the commands, it works perfectly.

test for port 8882 (not using virtual env)
<img width="1440" alt="image" src="https://user-images.githubusercontent.com/60949885/160625506-4204d03e-182c-496d-ac17-2ab505926a94.png">

test for port 8883 (using virtual env)
<img width="1440" alt="image" src="https://user-images.githubusercontent.com/60949885/160629074-7b5c0029-069d-489e-a5c6-5f6422389193.png">
 
runs ok using or not virtual enviroment. 

but in both cases I got this error running some examples

<img width="851" alt="image" src="https://user-images.githubusercontent.com/60949885/160629319-eda55fa6-fa9f-43a0-ae8b-1bf053208c6b.png">

**Comment by pescap** [comment]
> but in both cases I got this error running some examples
> 
> <img alt="image" width="851" src="https://user-images.githubusercontent.com/60949885/160629319-eda55fa6-fa9f-43a0-ae8b-1bf053208c6b.png">

`dde.icbc` was moved to `dde.icbcs`

**Comment by agustinesoto** [comment]
> Let me know if it works with you. Then, I'll let you add the final steps to the `docs`.

So should I start with the documentation of this issue?
