### ISSUE TITLE
Complete the documentation concerning ssh docker/jupyter-notebook

### ISSUE THREAD

**Issue by pescap** [pescap/EasyHPC#47]
Complete the documentation, insist on port forwarding, `lsof -i:a` with port `a`. Basic commands `docker stop` and `docker ps`

**Comment by pescap** [comment]
@Setol21 we can comment here the issues you have with ports. @agustinesoto has also been working on it.

**Comment by pescap** [comment]
In a terminal, you can run a script (e.g. `main.py`) with any [ddebackend](https://github.com/lululxvi/deepxde/blob/085fd9ee080082467e8415a286df1cdce6ce058e/deepxde/backend/set_default_backend.py#L28) and `GPU=3` with this command: 

`DDEBACKEND='tensorflow' CUDA_VISIBLE_DEVICES='3' python main.py`

**Comment by Setol21** [comment]
> In a terminal with deepxde env, you can run a script (e.g. `main.py`) with any [ddebackend](https://github.com/lululxvi/deepxde/blob/085fd9ee080082467e8415a286df1cdce6ce058e/deepxde/backend/set_default_backend.py#L28) and `GPU=3` with this command:
> 
> `DDEBACKEND='tensorflow' CUDA_VISIBLE_DEVICES='3' python main.py`

This worked, but I had to use "tensorflow-gpu" (even if I changed to another environment), because it requires tensorflow_probability and normal tensorflow doesn't have it, I guess I just have to update my tensorflow version?
- For my example (helmholtz) the 3rd gpu was using roughly 600MiB.
