### ISSUE TITLE
Small section about Neural networks and how they work.

### ISSUE THREAD

**Issue by Setol21** [pescap/EasyHPC#48]
It would be very nice if we add a section in our documentation to explain briefly what are NN and how they work.

I mean, not something very complicated, maybe that and also quick summary of key words, like epochs, nodes, weights, constraints, loss, etc.

**Comment by Ehaw04** [comment]
I would like to take this issue.

**Comment by ArtemioA** [comment]
I put information about it in another Issue.

I hope I can help you, Elias.

**Comment by ArtemioA** [comment]
The work is finished? I can take this issue

**Comment by ArtemioA** [comment]
![image](https://user-images.githubusercontent.com/78178128/162336960-e20ac28b-c427-49d7-b6b9-eb80d8bfe71b.png)

**Comment by ArtemioA** [comment]
I want put this into the documentation.
Please help me.

https://www.overleaf.com/read/rddtsxrjtxvh
