### ISSUE TITLE
Add basic code concerning Horovod

### ISSUE THREAD

**Issue by pescap** [pescap/EasyHPC#50]
Share what I implemented so far.

**Comment by pescap** [comment]
Run a docker-based `horovod` image:
```nvidia-docker run  -it horovod/horovod```

Go to the `tensorflow2` examples. 


Run for example: 


````
CUDA_VISIBLE_DEVICES=0,1,2,3,4,5,6,7 horovodrun -np 8 -H localhost:8 python tensorflow2_mnist.py
```

On 2 GPUs:


````
CUDA_VISIBLE_DEVICES=6,7 horovodrun -np 2 -H localhost:2 python tensorflow2_mnist.py
```

**Comment by pescap** [comment]
#58

**Comment by pescap** [comment]
@Setol21 @agustinesoto Try not to use GPU=2, I am running experiments on it. And beware with the Docker running on port 8888, those simulations last 4 days, I would prefer not to have to run them again!

**Comment by Setol21** [comment]
> @Setol21 @agustinesoto Try not to use `GPU='2'` as I am running intensive experiments on it. And beware with the Docker running on port 8888, those simulations last 4 days, I would prefer not to have to run them again!
> 

I don't get what do you mean by running the docker on port 8888.

```
nvidia-docker run -v $(pwd):/root/shared -w "/root/shared" -p d:e pescapil/deepxde:latest
```

In this command do you mean not using 8888 on 'd' or 'e'.

For now im trying to implement horovod on the helmholtz example (time independent).

**Comment by pescap** [comment]
Just be cautious with not stopping the `busy_babbage` Docker:

![Captura de Pantalla 2022-04-04 a la(s) 11 48 32](https://user-images.githubusercontent.com/14826266/161582352-23cb71c6-3174-48d1-aa41-2b4353537236.png)

**Comment by pescap** [comment]
> > Run a docker-based `horovod` image: `nvidia-docker run -it horovod/horovod`
> > Go to the `tensorflow2` examples.
> > Run for example:
> > ```
> > CUDA_VISIBLE_DEVICES=0,1,2,3,4,5,6,7 horovodrun -np 8 -H localhost:8 python tensorflow2_mnist.py
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > On 2 GPUs:
> > ```
> > CUDA_VISIBLE_DEVICES=6,7 horovodrun -np 2 -H localhost:2 python tensorflow2_mnist.py
> > ```
> 
> Just did that, it works well, now I will look into understand the code.
> 
> I will write everything that helps to add it to the documentation in the next days/week.

Do this to close this issue.
