### ISSUE TITLE
Add ssh key configuration section on Github section

### ISSUE THREAD

**Issue by Setol21** [pescap/EasyHPC#52]
@ArtemioA

**Comment by Setol21** [comment]
Maybe do this steps:

1. See your ssh key:
   $ cat ~/.ssh/id_rsa.pb
2. Add the ssh key to your profile.

If you don't have an ssh key:
   $ ssh-keygen
Press enter, enter again, and enter again.

**Comment by ArtemioA** [comment]
Listo

**Comment by Setol21** [comment]
Don't close the issue, you didn't submitted any pull requests.
Also, remember to use universal language!

**Comment by ArtemioA** [comment]
Finished. No problem.

**Comment by pescap** [comment]
@ArtemioA ?

**Comment by Ehaw04** [comment]
@ArtemioA  in order to close an issue you have to send a pull request modifying the current documentation related to the issue. This follows our workflow to keep improving this repo

**Comment by pescap** [comment]
@ArtemioA how are you going with this issue?

**Comment by pescap** [comment]
On my MacBook, I ran:

```
ssh-keygen -t rsa
```
And then:
```
ssh-copy-id -i ~/.ssh/id_rsa.pub user@my_ip_address
```

**Comment by ArtemioA** [comment]
This problem is not so that github can recognize that it is indeed me? I think I have solved this problem.

**Comment by pescap** [comment]
@ArtemioA
