### ISSUE TITLE
Libros & Reflexiones

### ISSUE THREAD

**Issue by ArtemioA** [pescap/EasyHPC#56]
Representación vectorizada de una red neuronal 
(usando el operador multiplicación matricial)

![image](https://user-images.githubusercontent.com/78178128/159599749-dd01f83c-3927-47fd-ad0c-2de8e4583079.png)

En esta foto pueden observar un perceptrón multicapa para estimar la masa de probabilidad propia de una distribución de Bernoulli asociada a una variable aleatoria ante un vector patrón de entrada s.

Yo mismo hice la representación vectorizada de este ejemplo práctico de una red neuronal.

Los valores Theta son los parámetros que nuestra red aprende con la muestra observada. 

Las funciones de activación como ReLU, Sigmoid, Tanh definen la transformación no lineal T_{1} y T_{2} adjuntada en la imagen. Asimismo, brinda a la red propiedades de adaptación para aproximarse a funciones complejas que no se veían en polinomios comunes y corrientes (cómo campos vectoriales y sus aplicaciones en la física).

- Observar que si los transformadores no lineales T_{1} y T_{2} fuesen funciones lineales, entonces la "red neuronal", **literalmente** no sería otra cosa que una representación vectorizada de un polinomio.

Como fundamento, recordemos en nuestras clases de Física cuando usábamos la idea central del Teorema de Taylor para aproximarnos a una función suave usando una serie de potencias (que es un polinomio), como una distribución de temperatura (en función del espacio), o coeficientes de transferencia de calor (en función del espacio), etc...

El planteamiento matemático del problema es muy similar al efectuado por el estadístico R.A. Fisher para estimar
los parámetros de una función de densidad o masa asociada a una variable aleatoria. ¿Cuáles deben ser los parámetros para que la probabilidad/densidad conjunta aumente al máximo?

![image](https://user-images.githubusercontent.com/78178128/159600736-c552c48d-19b5-4150-8c83-6c9fde6d7a96.png)

Esta función mide la verosimilitud de la muestra, o la probabilidad conjunta de la muestra suponiendo que la distribución generadora de la misma sea parametrizable (y las variables aleatorias independientes entre sí, entonces la probabilidad conjunta es la productoria de las probabilidades marginales (teorema)) con un perceptrón en función de un patrón vector de entrada s (x_{1},x_{2},...,x_{n}) en la imagen.

Un derivado matemático de dicha expresión es lo que denomina como la función de coste (Suponiendo que las variables aleatorias posean varianza constante, entonces la función tiende a adoptar una forma similar al "principio de mínimos cuadrados"). En este caso se tiende a usar logaritmos para representar la productoria como una suma, además de que en la práctica se evita que el algoritmo converja en mínimos locales. (Recordar que la función logarítmica es una función MONOTONA CRECIENTE, y por tanto no afecta la preferencia de unos parámetros por sobre otros, si nuestro criterio consiste en seleccionar aquel que posea la verosimilitud más alta).

El algoritmo backpropagation sirve para calcular la evaluación en el **GRADIENTE** de la función de coste con una concatenación de parámetros Theta de la red neuronal (matrices de números reales. Si. Números reales). En cada "Epoch", el algoritmo realiza este proceso ahorrando una cantidad considerable de poder computacional. Actualizando sus parámetros para minimizar la función de coste (idea propia de los algoritmos de descenso), y encontrar un modelo que pueda predecir nuevos valores eficientemente.

Me gustaría compartir acceso a unos libros que intentan recopilar gran parte de lo que hemos aprendido en otros cursos de manera conceptual (Estadística y Probabilidad, Optimización, Cálculo Multivariable, Álgebra Lineal) de manera unificada.

https://drive.google.com/drive/folders/1u9Zx3D0VTzrwnVfI-nQi-5hbJKxgqIQD?usp=sharing

Asimismo, encontrarán un tutorial hecho por Andrew Ng del año **2017** que da consejos sobre cómo entrenar eficientemente una red neuronal, para que no se sobreajuste a la muestra puntual observada.

Finalmente, me gustaría compartir unas reflexiones de un paper increíble de microeconomía que interpreta de una manera excepcional lo que son las funciones continuas, diferenciables como lo son las redes neuronales y sus derivados.

![image](https://user-images.githubusercontent.com/78178128/159609053-f97733c3-d447-4b10-ac99-0cd03e292cfa.png)

https://drive.google.com/file/d/14wxXzxrWOL7Ntz4NYaoTKBMxlKZffwc1/view?usp=sharing

Consejos para leer papers por Andrew Ng

https://www.youtube.com/watch?v=733m6qBH-jI

Adjunto un libro si a alguien le interesa la manipulación de variables aleatorias. Sería interesante en otra ocasión "reciclar" esta matemática antigua para crear algoritmos nunca antes vistos.
https://www.ime.usp.br/~jmstern/wp-content/uploads/2020/11/Springer1979.pdf

**Comment by pescap** [comment]
I suggest that you add part of these notes to the documentation.

Also, the Andrew Ng video is very interesting. A summarized version of it should appear somewhere in docs.
