### ISSUE TITLE
[HPC] Understand Horovod tutorials

### ISSUE THREAD

**Issue by pescap** [pescap/EasyHPC#58]
A few tasks for both of you:   

- [x] Reproduce [this section](https://github.com/pescap/EasyHPC/blob/main/docs/source/horovod.rst)
- [x] Understand `tensorflow2_synthetic_benchmark.py`
- [x] Understand `tensorflow2_keras_mnist.py` and its code. 
- [x] Create a benchmark for `tensorflow2_synthetic_benchmark.py` with respect to the number of GPUs. 
- [x] Add a table with the results

**Comment by pescap** [comment]
My comments.

The benchmark should be runned as a simple bash code. A sketch of the code:

`for d in 0.00001 0.00002 0.00003 0.00004
do
    DDEBACKEND='tensorflow' CUDA_VISIBLE_DEVICES=$(( ( RANDOM % 8 )  + 1 )) python dirichlet.py --name 'lr'${d} --learning_rate ${d}& 
done`

I used the code above to run a Python script with different learning rates in parallel. Here, `CUDA_VISIBLE_DEVICES` was set as a random number between 0 and 7.

Change the for loop to `for i = range(8)` (write this idea in bash) and define appropriately `CUDA_VISIBLE_DEVICES=` for each run, such that it gives:
= 0
= 0,1
= 0,1,2,
and so on.

Then, you can modify the python scripts, so as to store the execution times etc. somewhere. Let me know if you have further questions.


With respect to `tensorflow2_keras_mnist.py`, I don't really understand what changes when we put more GPUs. Understand what happends with the training data, where is the speedup, etc...

**Comment by pescap** [comment]
In parallel, also check [Accelerate](https://github.com/huggingface/accelerate). It sounds even easier than Horovod, but only works with PyTorch. It would be interesting comparing Acelerate and Horovod for multiple GPU! It has mixed precision, which could be interesting.

**Comment by Setol21** [comment]
As soon as I can finish the TensorFlow tutorial I will contribute to the Horovod documentation, I'm still struggling with the syntax of it, and therefore applying it to a simple model of DL.
