### ISSUE TITLE
Closing inactive issues

### ISSUE THREAD

**Issue by pescap** [pescap/EasyHPC#60]
I think it would be a good idea to close inactive issues. After how many days shall we close the issues? 7,10,15 days?

**Comment by pescap** [comment]
How to do that: https://docs.github.com/en/github-ae@latest/actions/managing-issues-and-pull-requests/closing-inactive-issues

**Comment by Setol21** [comment]
> I think it would be a good idea to close inactive issues. After how many days shall we close the issues? 7,10,15 days?

I think 15 days, sometimes is not that no one can close the issue, maybe it is for time purposes.
There are a few issues that I think are unclosable, like new sections. What do you think?

**Comment by pescap** [comment]
I decided to set:
7 days -> stale issue
7 days more -> close issue
