### ISSUE TITLE
Complete the vpn activation instructions for Windows+WSL2 (spanish)

### ISSUE THREAD

**Issue by pescap** [pescap/EasyHPC#61]
We could help the TI people, and add a paragraph to the original vpn set up instructions. Then, we will send the note to the UAI TI team, so that they add it to the instructions.

- [x] Create a shared google doc
- [x] Detail the proceeding for WSL2

**Comment by Setol21** [comment]
https://docs.google.com/document/d/1zGpOt8AKYiHis5dFq9AIdDxwcpUICs5Y-mwHuEvdkEQ/edit?usp=sharing

Here are the steps (in spanish) to make the VPN connections. This is no different than installing a updated version of AnyConnect, in this case from the Windows Store. This would work on Windows and WSL2.
