### ISSUE TITLE
Choose names for the new repositories

### ISSUE THREAD

**Issue by pescap** [pescap/EasyHPC#71]
Dear all, 
I am going to create new repositories for each TID: 
- Horovod PINNs
- Inverse Scattering PINNs

Let me know if you have any preferences and ideas for the names! I'll then create the repos.

**Comment by pescap** [comment]
The repos will be totally autonomous, and include CI/CD integration.

**Comment by Setol21** [comment]
> Dear all, I am going to create new repositories for each TID:
> 
>     * Horovod PINNs
> 
>     * Inverse Scattering PINNs
> 
> 
> Let me know if you have any preferences and ideas for the names! I'll then create the repos.

If I can come up with a name I will propose it, but my creativity is very poor haha

**Comment by Ehaw04** [comment]
I like ScattPINNs!

**Comment by pescap** [comment]
Someday, we will migrate these repositories to an organization.

https://github.com/pescap/FastDeepXDE

https://github.com/pescap/ScattPINNs
